# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

# Data-driven behavior suite: replays every shared behavior case through the
# request layer with a fake middleware transport. Schema-independent — the
# fixture in test/sdk-behavior-cases.json carries the per-operation detail.

require 'json'
require 'minitest/autorun'
require 'uri'
require 'octri_send_grid_mail'

class SdkBehaviorTest < Minitest::Test
  # Explicit UTF-8: the fixture holds non-ASCII values and the process default
  # external encoding is not guaranteed.
  FIXTURE = JSON.parse(File.read(File.join(__dir__, 'sdk-behavior-cases.json'), encoding: 'utf-8'))

  # Space is "+" in form encoding and "%20" under RFC 3986; both are accepted,
  # and pair order is not part of the contract.
  def normalize_query(raw)
    return '' if raw.nil? || raw.empty?

    URI.decode_www_form(raw.gsub('%20', '+')).sort.map { |name, value| "#{name}=#{value}" }.join('&')
  end

  def build_path(request_spec)
    path = request_spec['pathTemplate']
    request_spec['pathParameters'].each do |name, value|
      path = path.gsub("{#{name}}", OctriSendGridMail::SdkClient.encode_path_segment(value))
    end
    path
  end

  FIXTURE['cases'].each do |item|
    define_method("test_behavior_#{item['id'].gsub(/[^a-zA-Z0-9]/, '_')}") do
      request_spec = item['request']
      response_spec = item['response']
      seen = nil

      config = OctriSendGridMail::ClientConfig.new
      config.base_url = FIXTURE['baseUrl']
      auth = OctriSendGridMail::ClientAuthConfig.new
      auth.headers = FIXTURE['authHeaders'].dup
      config.auth = auth
      retry_config = OctriSendGridMail::RetryConfig.new
      retry_config.max_attempts = 1
      config.retry = retry_config
      idempotency = OctriSendGridMail::IdempotencyConfig.new
      idempotency.enabled = false
      config.idempotency = idempotency
      config.middleware = [lambda do |request, _next|
        seen = request
        headers = {}
        headers['content-type'] = response_spec['mediaType'] if response_spec['mediaType']
        OctriSendGridMail::SdkRawResponse.new(
          status_code: response_spec['status'],
          status_text: '',
          headers: headers,
          body: response_spec['status'] == 204 ? '' : response_spec['body'],
          request_id: nil,
          latency: 0.001,
          attempt: request.attempt
        )
      end]

      query = {}
      if request_spec
        request_spec['query'].each do |parameter|
          next if parameter['value'].nil?

          query[parameter['name']] = OctriSendGridMail::QueryValue.new(
            parameter['value'], style: parameter['style'], explode: parameter['explode']
          )
        end
      end

      method = request_spec ? request_spec['method'] : 'GET'
      path = request_spec ? build_path(request_spec) : "/behavior/#{item['id']}"
      options = {
        config: config,
        query: query,
        operation_id: item['operationId'],
        decoder: response_spec['kind'].to_sym
      }
      if request_spec
        options[:extra_headers] = request_spec['headers'] unless request_spec['headers'].empty?
        unless request_spec['bodyKind'].nil?
          options[:body] = request_spec['body']
          options[:content_type] = request_spec['contentType']
        end
      end

      if response_spec['status'] >= 400
        error = assert_raises(OctriSendGridMail::SdkHttpError) do
          OctriSendGridMail::SdkClient.request(method, path, **options)
        end
        assert_equal response_spec['status'], error.status_code
        assert_equal response_spec['value'], error.body if response_spec.key?('value')
      else
        response = OctriSendGridMail::SdkClient.request(method, path, **options)
        assert_equal response_spec['status'], response.status_code
        if response_spec.key?('value')
          expected = response_spec['value']
          actual = response.data
          actual = actual.to_s.bytesize if response_spec['kind'] == 'bytes'
          if expected.nil?
            assert_nil actual
          else
            assert_equal expected, actual
          end
        end
      end

      next unless request_spec

      refute_nil seen, 'middleware never saw a request'
      assert_equal item['expect']['method'], seen.method
      got_base, got_query = seen.url.split('?', 2)
      want_base, want_query = item['expect']['url'].split('?', 2)
      assert_equal want_base, got_base
      assert_equal normalize_query(want_query), normalize_query(got_query)
      item['expect']['headers'].each do |name, value|
        actual = seen.headers.find { |header, _| header.downcase == name }&.last
        if name == 'content-type' && !item['expect']['multipartFields'].nil?
          assert actual.to_s.start_with?('multipart/form-data'), 'multipart content type'
          next
        end
        assert_equal value, actual, "header #{name}"
      end
      if !item['expect']['bodyText'].nil? && request_spec['bodyKind'] == 'json'
        assert_equal JSON.parse(item['expect']['bodyText']), JSON.parse(seen.body)
      end
    end
  end
end
