# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

require 'minitest/autorun'
require 'octri_send_grid_mail'

class SdkRuntimeTest < Minitest::Test
  def test_path_segment_encoding
    assert_equal '%2F%20%3F%23%25%E9%9B%AA', OctriSendGridMail::SdkClient.encode_path_segment('/ ?#%雪')
  end

  def test_query_array_styles
    query = OctriSendGridMail::SdkClient.build_query_string(
      repeated: OctriSendGridMail::QueryValue.new(%w[a 雪], explode: true),
      csv: OctriSendGridMail::QueryValue.new(%w[a b], explode: false)
    )
    assert_includes query, 'repeated=a&repeated=%E9%9B%AA'
    assert_includes query, 'csv=a%2Cb'
  end

  def test_response_decoders
    assert_equal "\x00raw".b, OctriSendGridMail::SdkClient.decode_body("\x00raw".b, :bytes, nil)
    assert_equal 'hello', OctriSendGridMail::SdkClient.decode_body('hello', :text, nil)
    assert_nil OctriSendGridMail::SdkClient.decode_body('', :empty, nil)
  end

  def test_request_layer_uses_fake_middleware
    config = OctriSendGridMail::ClientConfig.new
    config.base_url = 'https://example.test'
    config.middleware = [lambda do |request, _next|
      assert_equal 'GET', request.method
      assert_equal 'https://example.test/probe', request.url
      OctriSendGridMail::SdkRawResponse.new(
        status_code: 200, status_text: 'OK', headers: { 'x-request-id' => 'fake-id' },
        body: '{"ok":true}', request_id: 'fake-id', latency: 0.001, attempt: request.attempt
      )
    end]
    response = OctriSendGridMail::SdkClient.request('GET', '/probe', config: config, operation_id: 'probe')
    assert_equal true, response.data['ok']
    assert_equal 'fake-id', response.request_id
  end
end
