# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

require 'json'
require 'octri_send_grid_mail'
require 'minitest/autorun'

class SdkMethodTest < Minitest::Test
  CASES = JSON.parse(File.read(File.expand_path('../test/sdk-method-cases.json', __dir__)))['cases']

  def normalized(value)
    value.to_s.downcase.gsub(/[^a-z0-9]/, '')
  end

  def normal(value)
    # NilClass answers to_h with an empty hash, so a decoded null would read as
    # {} and never match the fixture's null.
    return nil if value.nil?
    return value.map { |child| normal(child) } if value.is_a?(Array)
    return value.to_h.transform_values { |child| normal(child) } if value.respond_to?(:to_h)
    return value.transform_values { |child| normal(child) } if value.is_a?(Hash)

    value
  end

  def representative?(actual, expected)
    if expected.is_a?(Hash)
      return false unless actual.is_a?(Hash)

      indexed = actual.to_h.transform_keys { |key| normalized(key) }
      return expected.all? do |key, value|
        indexed.key?(normalized(key)) && representative?(indexed[normalized(key)], value)
      end
    end
    if expected.is_a?(Array)
      return actual.is_a?(Array) && actual.length == expected.length &&
             expected.each_index.all? { |index| representative?(actual[index], expected[index]) }
    end
    actual == expected
  end

  def test_every_generated_method_reaches_mock_and_decodes_its_response
    base_url = ENV.fetch('SDK_METHOD_TEST_BASE_URL', nil)
    skip 'Run ./scripts/test to start the generated mock server.' if base_url.nil? || base_url.empty?

    config = OctriSendGridMail::ClientConfig.new
    config.base_url = base_url
    OctriSendGridMail::SdkConfig.configure(config)
    refute_empty CASES
    CASES.each do |test_case|
      owner = test_case['owner'].split('::').inject(Object) { |scope, name| scope.const_get(name) }
      callable = owner.method(test_case['methodName'])
      arguments = test_case['arguments'].transform_keys(&:to_sym)
      positional = []
      keywords = {}
      callable.parameters.each_with_index do |(kind, name), index|
        next if kind == :block

        value = if normalized(name).include?('config')
                  OctriSendGridMail::SdkConfig.config
                elsif %i[params options request].include?(name)
                  arguments
                else
                  key = arguments.keys.find { |candidate| normalized(candidate) == normalized(name) }
                  key ||= test_case['argumentOrder'][index]&.to_sym
                  arguments[key]
                end
        if %i[key keyreq].include?(kind)
          keywords[name] = value
        elsif kind == :keyrest
          keywords.merge!(arguments)
        else
          positional << value
        end
      end
      actual = callable.call(*positional, **keywords)
      actual = actual.first if test_case['mode'] == 'stream' && actual.respond_to?(:first)
      response = test_case['response']
      if response['kind'] == 'empty'
        assert_nil actual, test_case['id']
      elsif response['kind'] == 'bytes'
        assert_equal response['byteLength'], actual.bytesize, test_case['id']
      else
        assert representative?(normal(actual), response['expected']),
               "#{test_case['id']} decoded a response that differs from the mock"
      end
    end
  end
end
