# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

# shared domain models
module OctriSendGridMail
  # Internal model hydration metadata.
  class SdkInternalErrorResponseErrorsItemMetadata
    FIELDS = {
      message: 'message',
      field: 'field',
      help: 'help'
    }.freeze
    REQUIRED_FIELDS = %i[].freeze
    DECODERS = {}.freeze
  end

  # API model for ErrorResponseErrorsItem.
  # Required object value serialized in the `errors[]` wire field.
  class ErrorResponseErrorsItem
    CONSTRUCTION_SURFACE = :named
    FIELDS = SdkInternalErrorResponseErrorsItemMetadata::FIELDS
    REQUIRED_FIELDS = SdkInternalErrorResponseErrorsItemMetadata::REQUIRED_FIELDS
    DECODERS = SdkInternalErrorResponseErrorsItemMetadata::DECODERS

    # @return [String] An error message.
    attr_reader :message
    # @return [String] When applicable, this property value will be the field that generated the error.
    attr_reader :field
    # @return [Hash] When applicable, this property value will be helper text or a link to documentation to help you troubleshoot the error.
    attr_reader :help

    def initialize(**attributes)
      SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
      freeze
    end

    def self.from_hash(data)
      SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
    end

    def to_h
      SdkModel.to_h(self, FIELDS)
    end
  end

  # Internal model hydration metadata.
  class SdkInternalErrorResponseMetadata
    FIELDS = {
      errors: 'errors',
      id: 'id'
    }.freeze
    REQUIRED_FIELDS = %i[].freeze
    DECODERS = {
      errors: lambda do |value|
        value&.map { |item| ::OctriSendGridMail::ErrorResponseErrorsItem.from_hash(item) }
      end
    }.freeze
  end

  # API model for ErrorResponse.
  # Typed representation of the `ErrorResponse` API schema.
  class ErrorResponse
    CONSTRUCTION_SURFACE = :named
    FIELDS = SdkInternalErrorResponseMetadata::FIELDS
    REQUIRED_FIELDS = SdkInternalErrorResponseMetadata::REQUIRED_FIELDS
    DECODERS = SdkInternalErrorResponseMetadata::DECODERS

    # @return [Array_of_ErrorResponseErrorsItem] Optional array value serialized in the `errors` wire field.
    attr_reader :errors
    # @return [String] When applicable, this property value will be an error ID.
    attr_reader :id

    def initialize(**attributes)
      SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
      freeze
    end

    def self.from_hash(data)
      SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
    end

    def to_h
      SdkModel.to_h(self, FIELDS)
    end
  end
end
