# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

# Defines the OctriSendGridMail SDK namespace.
module OctriSendGridMail
  # Defines the Methods SDK namespace.
  module Methods
    # Defines the MailBatch SDK namespace.
    module MailBatch
      # **This operation allows you to generate a new mail batch ID.** Once a batch ID is created, you can associate it with a mail send by passing it in the request body of the Mail Send operation. This makes it possible to group multiple requests to the Mail Send operation by assigning them the same batch ID. A batch ID that's associated with a mail send can be used to access and modify the associated send. For example, you can pause or cancel a send using its batch ID. See the…
      #
      # @param on_behalf_of [String] Use the `on-behalf-of` header to make API calls
      #   for a particular Subuser through the parent account. You can use this header
      #   to automate bulk updates or to administer a Subuser without changing the
      #   authentication in your code. You will use the parent account's API key when
      #   using this header.
      def self.create_mail_batch(
        config:,
        on_behalf_of: NOT_GIVEN
      )

        SdkClient.request(
          'POST',
          "/v3/mail/batch",
          config: config,
          return_type: MailBatchResponse,
          decoder: :json,
          operation_id: 'create_mail_batch',
          extra_headers: SdkClient.serialize_headers({
            'on-behalf-of' => on_behalf_of,
          }),
        ).data
      end

      # **This operation allows you to validate a mail batch ID.** If you provide a valid batch ID, this operation will return a `200` status code and the batch ID itself. If you provide an invalid batch ID, you will receive a `400` level status code and an error message. A batch ID does not need to be assigned to a send to be considered valid. A successful response means only that the batch ID has been created, but it does not indicate that the ID has been assigned to a send.
      #
      # @param batch_id [String] Set this parameter to the batch ID that's
      #   associated with the mail send you want to retrieve.
      # @param on_behalf_of [String] Use the `on-behalf-of` header to make API calls
      #   for a particular Subuser through the parent account. You can use this header
      #   to automate bulk updates or to administer a Subuser without changing the
      #   authentication in your code. You will use the parent account's API key when
      #   using this header.
      singleton_class.define_method(:get_mail_batch) do |
        config:,
        batch_id:,
        on_behalf_of: NOT_GIVEN
      |

        SdkClient.request(
          'GET',
          [
            "/v3/mail/batch/",
            SdkClient.encode_path_segment(batch_id)
          ].join,
          config: config,
          return_type: MailBatchResponse,
          decoder: :json,
          operation_id: 'get_mail_batch',
          extra_headers: SdkClient.serialize_headers({
            'on-behalf-of' => on_behalf_of,
          }),
        ).data
      end
    end
  end
end
