# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

# Defines the OctriSendGridMail SDK namespace.
module OctriSendGridMail
  # Defines the Methods SDK namespace.
  module Methods
    # Defines the MailSend SDK namespace.
    module MailSend
      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaAsmMetadata
        FIELDS = {
          group_id: "group_id",
          groups_to_display: "groups_to_display",
        }.freeze
        REQUIRED_FIELDS = %i[
          group_id
        ].freeze
        DECODERS = {
        }.freeze
      end

      # API model for SchemaSchemaAsm.
      # An object allowing you to specify how to handle unsubscribes. With SendGrid, an unsubscribe is the action an email recipient takes when they opt-out of receiving your messages. A suppression is the action you take as a sender to filter or suppress an unsubscribed address from your email send. From the perspective of the recipient, your suppression is the result of their unsubscribe. See **Suppression Groups** for more information.
      class SchemaSchemaAsm
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaAsmMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaAsmMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaAsmMetadata::DECODERS

        # @return [Integer] The unsubscribe group to associate with this email. See the Suppressions API to manage unsubscribe group IDs.
        attr_reader :group_id
        # @return [Array_of_Integer] An array containing the unsubscribe groups that you would like to be displayed to a recipient on the unsubscribe preferences page. This page is displayed in the recipient's browser when they click the unsubscribe link in your message.
        attr_reader :groups_to_display

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaMailSettingsBypassListManagementMetadata
        FIELDS = {
          enable: "enable",
        }.freeze
        REQUIRED_FIELDS = %i[
        ].freeze
        DECODERS = {
        }.freeze
      end

      # API model for SchemaSchemaMailSettingsBypassListManagement.
      # Allows you to bypass all unsubscribe groups and suppressions to ensure that the email is delivered to every single recipient. This should only be used in emergencies when it is absolutely necessary that every recipient receives your email. This filter cannot be combined with any other bypass filters. See the the "Bypass suppressions" section of our **Suppressions Overview** for more about bypass filters.
      class SchemaSchemaMailSettingsBypassListManagement
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaMailSettingsBypassListManagementMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaMailSettingsBypassListManagementMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaMailSettingsBypassListManagementMetadata::DECODERS

        # @return [Boolean] Indicates if this setting is enabled.
        attr_reader :enable

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaMailSettingsBypassSpamManagementMetadata
        FIELDS = {
          enable: "enable",
        }.freeze
        REQUIRED_FIELDS = %i[
        ].freeze
        DECODERS = {
        }.freeze
      end

      # API model for SchemaSchemaMailSettingsBypassSpamManagement.
      # Allows you to bypass the spam report list to ensure that the email is delivered to recipients. Bounce and unsubscribe lists will still be checked; addresses on these other lists will not receive the message. This filter cannot be combined with the `bypass_list_management` filter. See the the "Bypass suppressions" section of our **Suppressions Overview** for more about bypass filters.
      class SchemaSchemaMailSettingsBypassSpamManagement
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaMailSettingsBypassSpamManagementMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaMailSettingsBypassSpamManagementMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaMailSettingsBypassSpamManagementMetadata::DECODERS

        # @return [Boolean] Indicates if this setting is enabled.
        attr_reader :enable

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaMailSettingsBypassBounceManagementMetadata
        FIELDS = {
          enable: "enable",
        }.freeze
        REQUIRED_FIELDS = %i[
        ].freeze
        DECODERS = {
        }.freeze
      end

      # API model for SchemaSchemaMailSettingsBypassBounceManagement.
      # Allows you to bypass the bounce list to ensure that the email is delivered to recipients. Spam report and unsubscribe lists will still be checked; addresses on these other lists will not receive the message. This filter cannot be combined with the `bypass_list_management` filter. See the the "Bypass suppressions" section of our **Suppressions Overview** for more about bypass filters.
      class SchemaSchemaMailSettingsBypassBounceManagement
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaMailSettingsBypassBounceManagementMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaMailSettingsBypassBounceManagementMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaMailSettingsBypassBounceManagementMetadata::DECODERS

        # @return [Boolean] Indicates if this setting is enabled.
        attr_reader :enable

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaMailSettingsBypassUnsubscribeManagementMetadata
        FIELDS = {
          enable: "enable",
        }.freeze
        REQUIRED_FIELDS = %i[
        ].freeze
        DECODERS = {
        }.freeze
      end

      # API model for SchemaSchemaMailSettingsBypassUnsubscribeManagement.
      # Allows you to bypass the global unsubscribe list to ensure that the email is delivered to recipients. Bounce and spam report lists will still be checked; addresses on these other lists will not receive the message. This filter applies only to global unsubscribes and will not bypass group unsubscribes. This filter cannot be combined with the `bypass_list_management` filter. See the the "Bypass suppressions" section of our **Suppressions Overview** for more about bypass…
      class SchemaSchemaMailSettingsBypassUnsubscribeManagement
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaMailSettingsBypassUnsubscribeManagementMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaMailSettingsBypassUnsubscribeManagementMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaMailSettingsBypassUnsubscribeManagementMetadata::DECODERS

        # @return [Boolean] Indicates if this setting is enabled.
        attr_reader :enable

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaMailSettingsFooterMetadata
        FIELDS = {
          enable: "enable",
          text: "text",
          html: "html",
        }.freeze
        REQUIRED_FIELDS = %i[
        ].freeze
        DECODERS = {
        }.freeze
      end

      # API model for SchemaSchemaMailSettingsFooter.
      # Inserts a custom footer at the bottom of the text and HTML bodies of your messages. Use the `html` and `text` properties to include the content of the footers to be inserted.
      class SchemaSchemaMailSettingsFooter
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaMailSettingsFooterMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaMailSettingsFooterMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaMailSettingsFooterMetadata::DECODERS

        # @return [Boolean] Indicates if this setting is enabled.
        attr_reader :enable
        # @return [String] The plain text content of your footer.
        attr_reader :text
        # @return [String] The HTML content of your footer.
        attr_reader :html

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaMailSettingsSandboxModeMetadata
        FIELDS = {
          enable: "enable",
        }.freeze
        REQUIRED_FIELDS = %i[
        ].freeze
        DECODERS = {
        }.freeze
      end

      # API model for SchemaSchemaMailSettingsSandboxMode.
      # Sandbox Mode allows you to send a test email to ensure that your request body is valid and formatted correctly.
      class SchemaSchemaMailSettingsSandboxMode
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaMailSettingsSandboxModeMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaMailSettingsSandboxModeMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaMailSettingsSandboxModeMetadata::DECODERS

        # @return [Boolean] Indicates if this setting is enabled.
        attr_reader :enable

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaMailSettingsMetadata
        FIELDS = {
          bypass_list_management: "bypass_list_management",
          bypass_spam_management: "bypass_spam_management",
          bypass_bounce_management: "bypass_bounce_management",
          bypass_unsubscribe_management: "bypass_unsubscribe_management",
          footer: "footer",
          sandbox_mode: "sandbox_mode",
        }.freeze
        REQUIRED_FIELDS = %i[
        ].freeze
        DECODERS = {
          bypass_list_management: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaMailSettingsBypassListManagement.from_hash(value)
          end,
          bypass_spam_management: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaMailSettingsBypassSpamManagement.from_hash(value)
          end,
          bypass_bounce_management: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaMailSettingsBypassBounceManagement.from_hash(value)
          end,
          bypass_unsubscribe_management: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaMailSettingsBypassUnsubscribeManagement.from_hash(value)
          end,
          footer: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaMailSettingsFooter.from_hash(value)
          end,
          sandbox_mode: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaMailSettingsSandboxMode.from_hash(value)
          end,
        }.freeze
      end

      # API model for SchemaSchemaMailSettings.
      # A collection of different mail settings that you can use to specify how you would like this email to be handled. Mail settings provide extra functionality to your mail send. See **Mail Settings** for more information.
      class SchemaSchemaMailSettings
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaMailSettingsMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaMailSettingsMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaMailSettingsMetadata::DECODERS

        # @return [SchemaSchemaMailSettingsBypassListManagement] Allows you to bypass all unsubscribe groups and suppressions to ensure that the email is delivered to every single recipient. This should only be used in emergencies when it is absolutely necessary that every recipient receives your email. This filter cannot be combined with any other bypass filters. See the the "Bypass suppressions" section of our **Suppressions Overview** for more about bypass filters.
        attr_reader :bypass_list_management
        # @return [SchemaSchemaMailSettingsBypassSpamManagement] Allows you to bypass the spam report list to ensure that the email is delivered to recipients. Bounce and unsubscribe lists will still be checked; addresses on these other lists will not receive the message. This filter cannot be combined with the `bypass_list_management` filter. See the the "Bypass suppressions" section of our **Suppressions Overview** for more about bypass filters.
        attr_reader :bypass_spam_management
        # @return [SchemaSchemaMailSettingsBypassBounceManagement] Allows you to bypass the bounce list to ensure that the email is delivered to recipients. Spam report and unsubscribe lists will still be checked; addresses on these other lists will not receive the message. This filter cannot be combined with the `bypass_list_management` filter. See the the "Bypass suppressions" section of our **Suppressions Overview** for more about bypass filters.
        attr_reader :bypass_bounce_management
        # @return [SchemaSchemaMailSettingsBypassUnsubscribeManagement] Allows you to bypass the global unsubscribe list to ensure that the email is delivered to recipients. Bounce and spam report lists will still be checked; addresses on these other lists will not receive the message. This filter applies only to global unsubscribes and will not bypass group unsubscribes. This filter cannot be combined with the `bypass_list_management` filter. See the the "Bypass suppressions" section of our **Suppressions Overview** for more about bypass…
        attr_reader :bypass_unsubscribe_management
        # @return [SchemaSchemaMailSettingsFooter] Inserts a custom footer at the bottom of the text and HTML bodies of your messages. Use the `html` and `text` properties to include the content of the footers to be inserted.
        attr_reader :footer
        # @return [SchemaSchemaMailSettingsSandboxMode] Sandbox Mode allows you to send a test email to ensure that your request body is valid and formatted correctly.
        attr_reader :sandbox_mode

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaTrackingSettingsClickTrackingMetadata
        FIELDS = {
          enable: "enable",
          enable_text: "enable_text",
        }.freeze
        REQUIRED_FIELDS = %i[
        ].freeze
        DECODERS = {
        }.freeze
      end

      # API model for SchemaSchemaTrackingSettingsClickTracking.
      # Allows you to track if a recipient clicked a link in your email.
      class SchemaSchemaTrackingSettingsClickTracking
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaTrackingSettingsClickTrackingMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaTrackingSettingsClickTrackingMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaTrackingSettingsClickTrackingMetadata::DECODERS

        # @return [Boolean] Indicates if this setting is enabled.
        attr_reader :enable
        # @return [Boolean] Indicates if this setting should be included in the `text/plain` portion of your email.
        attr_reader :enable_text

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaTrackingSettingsOpenTrackingMetadata
        FIELDS = {
          enable: "enable",
          substitution_tag: "substitution_tag",
        }.freeze
        REQUIRED_FIELDS = %i[
        ].freeze
        DECODERS = {
        }.freeze
      end

      # API model for SchemaSchemaTrackingSettingsOpenTracking.
      # Allows you to track if the email was opened by including a single transparent pixel image in the body of the message content. When the message is opened, a request for the pixel is sent. That request indicates to Twilio SendGrid that the message was opened.
      class SchemaSchemaTrackingSettingsOpenTracking
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaTrackingSettingsOpenTrackingMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaTrackingSettingsOpenTrackingMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaTrackingSettingsOpenTrackingMetadata::DECODERS

        # @return [Boolean] Indicates if this setting is enabled.
        attr_reader :enable
        # @return [String] Allows you to specify a substitution tag that you can insert in the body of your email at a location that you desire. This tag will be replaced by the open tracking pixel.
        attr_reader :substitution_tag

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaTrackingSettingsSubscriptionTrackingMetadata
        FIELDS = {
          enable: "enable",
          text: "text",
          html: "html",
          substitution_tag: "substitution_tag",
        }.freeze
        REQUIRED_FIELDS = %i[
        ].freeze
        DECODERS = {
        }.freeze
      end

      # API model for SchemaSchemaTrackingSettingsSubscriptionTracking.
      # Allows you to insert a subscription management link at the bottom of the text and HTML bodies of your email. If you would like to specify the location of the link within your email, you may use the `substitution_tag` property.
      class SchemaSchemaTrackingSettingsSubscriptionTracking
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaTrackingSettingsSubscriptionTrackingMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaTrackingSettingsSubscriptionTrackingMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaTrackingSettingsSubscriptionTrackingMetadata::DECODERS

        # @return [Boolean] Indicates if this setting is enabled.
        attr_reader :enable
        # @return [String] Text to be appended to the email with the subscription tracking link.
        attr_reader :text
        # @return [String] HTML to be appended to the email with the subscription tracking link.
        attr_reader :html
        # @return [String] A tag that will be replaced with the unsubscribe URL. If this property is used, it will override both the `text` and `html` properties. The URL of the link will be placed at the substitution tag's location in the message body with no additional formatting.
        attr_reader :substitution_tag

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaTrackingSettingsGanalyticsMetadata
        FIELDS = {
          enable: "enable",
          utm_source: "utm_source",
          utm_medium: "utm_medium",
          utm_term: "utm_term",
          utm_content: "utm_content",
          utm_campaign: "utm_campaign",
        }.freeze
        REQUIRED_FIELDS = %i[
        ].freeze
        DECODERS = {
        }.freeze
      end

      # API model for SchemaSchemaTrackingSettingsGanalytics.
      # Allows you to enable tracking provided by Google Analytics. See **Google Analytics and SendGrid Statistics** for more information about this property.
      class SchemaSchemaTrackingSettingsGanalytics
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaTrackingSettingsGanalyticsMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaTrackingSettingsGanalyticsMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaTrackingSettingsGanalyticsMetadata::DECODERS

        # @return [Boolean] Indicates if this setting is enabled.
        attr_reader :enable
        # @return [String] Name of the referrer source. (e.g., Google, SomeDomain.com, or Marketing Email)
        attr_reader :utm_source
        # @return [String] Name of the marketing medium. (e.g., Email)
        attr_reader :utm_medium
        # @return [String] Used to identify any paid keywords.
        attr_reader :utm_term
        # @return [String] Used to differentiate your campaign from advertisements.
        attr_reader :utm_content
        # @return [String] The name of the campaign.
        attr_reader :utm_campaign

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaTrackingSettingsMetadata
        FIELDS = {
          click_tracking: "click_tracking",
          open_tracking: "open_tracking",
          subscription_tracking: "subscription_tracking",
          ganalytics: "ganalytics",
        }.freeze
        REQUIRED_FIELDS = %i[
        ].freeze
        DECODERS = {
          click_tracking: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaTrackingSettingsClickTracking.from_hash(value)
          end,
          open_tracking: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaTrackingSettingsOpenTracking.from_hash(value)
          end,
          subscription_tracking: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaTrackingSettingsSubscriptionTracking.from_hash(value)
          end,
          ganalytics: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaTrackingSettingsGanalytics.from_hash(value)
          end,
        }.freeze
      end
    end
  end
end

require_relative 'mail_send_part_2'
