# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

# Defines the OctriSendGridMail SDK namespace.
module OctriSendGridMail
  # Defines the Methods SDK namespace.
  module Methods
    # Defines the MailSend SDK namespace.
    module MailSend
      # API model for SchemaSchemaTrackingSettings.
      # Settings to determine how you would like to track the metrics of how your recipients interact with your email. See **Tracking Settings** for more information.
      class SchemaSchemaTrackingSettings
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaTrackingSettingsMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaTrackingSettingsMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaTrackingSettingsMetadata::DECODERS

        # @return [SchemaSchemaTrackingSettingsClickTracking] Allows you to track if a recipient clicked a link in your email.
        attr_reader :click_tracking
        # @return [SchemaSchemaTrackingSettingsOpenTracking] Allows you to track if the email was opened by including a single transparent pixel image in the body of the message content. When the message is opened, a request for the pixel is sent. That request indicates to Twilio SendGrid that the message was opened.
        attr_reader :open_tracking
        # @return [SchemaSchemaTrackingSettingsSubscriptionTracking] Allows you to insert a subscription management link at the bottom of the text and HTML bodies of your email. If you would like to specify the location of the link within your email, you may use the `substitution_tag` property.
        attr_reader :subscription_tracking
        # @return [SchemaSchemaTrackingSettingsGanalytics] Allows you to enable tracking provided by Google Analytics. See **Google Analytics and SendGrid Statistics** for more information about this property.
        attr_reader :ganalytics

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaPersonalizationsItemMetadata
        FIELDS = {
          from: "from",
          to: "to",
          cc: "cc",
          bcc: "bcc",
          subject: "subject",
          headers: "headers",
          substitutions: "substitutions",
          dynamic_template_data: "dynamic_template_data",
          custom_args: "custom_args",
          send_at: "send_at",
        }.freeze
        REQUIRED_FIELDS = %i[
          to
        ].freeze
        DECODERS = {
          from: lambda do |value|
            ::OctriSendGridMail::MailFrom.from_hash(value)
          end,
          to: lambda do |value|
            value&.map { |item| ::OctriSendGridMail::MailTo.from_hash(item) }
          end,
          cc: lambda do |value|
            value&.map { |item| ::OctriSendGridMail::MailTo.from_hash(item) }
          end,
          bcc: lambda do |value|
            value&.map { |item| ::OctriSendGridMail::MailTo.from_hash(item) }
          end,
        }.freeze
      end

      # API model for SchemaSchemaPersonalizationsItem.
      class SchemaSchemaPersonalizationsItem
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaPersonalizationsItemMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaPersonalizationsItemMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaPersonalizationsItemMetadata::DECODERS

        attr_reader :from
        # @return [Array_of_MailTo] An array of recipients to whom the email will be sent. Each object in this array must contain a recipient's email address. Each object in the array may optionally contain a recipient's name.
        attr_reader :to
        # @return [Array_of_MailTo] An array of recipients to whom a copy of the email will be sent. Each object in this array must contain a recipient's email address. Each object in the array may optionally contain a recipient's name.
        attr_reader :cc
        # @return [Array_of_MailTo] An array of recipients to whom a blind carbon copy of your email will be sent. Each object in this array must contain a recipient's email address. Each object in the array may optionally contain a recipient's name.
        attr_reader :bcc
        # @return [String] The subject of your email. See line length limits specified in RFC 2822 for guidance on subject line character limits.
        attr_reader :subject
        # @return [Hash] A collection of JSON property name and property value pairs allowing you to specify handling instructions for your email. You may not override the following headers: `x-sg-id`, `x-sg-eid`, `received`, `dkim-signature`, `Content-Type`, `Content-Transfer-Encoding`, `To`, `From`, `Subject`, `Reply-To`, `CC`, `BCC`.
        attr_reader :headers
        # @return [Hash] A collection property names that will be substituted by their corresponding property values in the `subject`, `reply-to` and `content` portions of your message. Name and value pairs follow the pattern `"substitution_tag":"value to substitute"`. The total collective size of your substitutions may not exceed 10,000 bytes per personalization object. Substitutions allow you to insert data without using SendGrid's Dynamic Templates. This property should not be used in combination…
        attr_reader :substitutions
        # @return [Hash] A collection property names that will be substituted by their corresponding property values in the `subject`, `reply-to` and `content` portions of a SendGrid Dynamic Template. Dynamic template data is available in a template using Handlebars syntax. This property should be used in combination with a Dynamic Template, which can be identified by a `template_id` starting with `d-`. See **How to Send an Email with Dynamic Templates** for more information.
        attr_reader :dynamic_template_data
        # @return [Hash] Values that are specific to this personalization that will be carried along with the email and its activity data. Substitutions will not be made on custom arguments, so any string that is assigned to this property will be assumed to be the custom argument that you would like to be used. This field may not exceed 10,000 bytes.
        attr_reader :custom_args
        # @return [Integer] A unix timestamp allowing you to specify when your email should be sent. A send cannot be scheduled more than 72 hours in advance.
        attr_reader :send_at

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaContentItemMetadata
        FIELDS = {
          type: "type",
          value: "value",
        }.freeze
        REQUIRED_FIELDS = %i[
          type
          value
        ].freeze
        DECODERS = {
        }.freeze
      end

      # API model for SchemaSchemaContentItem.
      class SchemaSchemaContentItem
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaContentItemMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaContentItemMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaContentItemMetadata::DECODERS

        # @return [String] The MIME type of the content assigned in the `value` property of this object (e.g., `text/plain` or `text/html`).
        attr_reader :type
        # @return [String] The content of your message in the specified MIME type assigned in the `type` property of this object.
        attr_reader :value

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaAttachmentsItemMetadata
        FIELDS = {
          content: "content",
          type: "type",
          filename: "filename",
          disposition: "disposition",
          content_id: "content_id",
        }.freeze
        REQUIRED_FIELDS = %i[
          content
          filename
        ].freeze
        DECODERS = {
          disposition: lambda do |value|
            ::OctriSendGridMail::Disposition.from_value(value)
          end,
        }.freeze
      end

      # API model for SchemaSchemaAttachmentsItem.
      class SchemaSchemaAttachmentsItem
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaAttachmentsItemMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaAttachmentsItemMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaAttachmentsItemMetadata::DECODERS

        # @return [String] The Base64 encoded content of the attachment.
        attr_reader :content
        # @return [String] The MIME type of the content you are attaching (e.g., `image/jpeg` or `application/pdf`).
        attr_reader :type
        # @return [String] The attachment's filename, including the file extension.
        attr_reader :filename
        # @return [Disposition] The attachment's content-disposition specifies how you would like the attachment to be displayed. For example, `inline` results in the attached file being displayed automatically within the message while `attachment` results in the attached file requiring some action to be taken before it is displayed such as opening or downloading the file.
        attr_reader :disposition
        # @return [String] The attachment's content ID. The `content_id` is used when the `disposition` is set to `inline` and the attachment is an image, allowing the file to be displayed within the body of the email.
        attr_reader :content_id

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Internal model hydration metadata.
      class SdkInternalSchemaSchemaMetadata
        FIELDS = {
          personalizations: "personalizations",
          from: "from",
          reply_to: "reply_to",
          reply_to_list: "reply_to_list",
          subject: "subject",
          content: "content",
          attachments: "attachments",
          template_id: "template_id",
          headers: "headers",
          categories: "categories",
          custom_args: "custom_args",
          send_at: "send_at",
          batch_id: "batch_id",
          asm: "asm",
          ip_pool_name: "ip_pool_name",
          mail_settings: "mail_settings",
          tracking_settings: "tracking_settings",
        }.freeze
        REQUIRED_FIELDS = %i[
          personalizations
          from
        ].freeze
        DECODERS = {
          personalizations: lambda do |value|
            value&.map { |item| ::OctriSendGridMail::Methods::MailSend::SchemaSchemaPersonalizationsItem.from_hash(item) }
          end,
          from: lambda do |value|
            ::OctriSendGridMail::MailFrom.from_hash(value)
          end,
          reply_to: lambda do |value|
            ::OctriSendGridMail::MailTo.from_hash(value)
          end,
          reply_to_list: lambda do |value|
            value&.map { |item| ::OctriSendGridMail::MailTo.from_hash(item) }
          end,
          content: lambda do |value|
            value&.map { |item| ::OctriSendGridMail::Methods::MailSend::SchemaSchemaContentItem.from_hash(item) }
          end,
          attachments: lambda do |value|
            value&.map { |item| ::OctriSendGridMail::Methods::MailSend::SchemaSchemaAttachmentsItem.from_hash(item) }
          end,
          asm: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaAsm.from_hash(value)
          end,
          mail_settings: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaMailSettings.from_hash(value)
          end,
          tracking_settings: lambda do |value|
            ::OctriSendGridMail::Methods::MailSend::SchemaSchemaTrackingSettings.from_hash(value)
          end,
        }.freeze
      end

      # API model for SchemaSchema.
      class SchemaSchema
        CONSTRUCTION_SURFACE = :named
        FIELDS = SdkInternalSchemaSchemaMetadata::FIELDS
        REQUIRED_FIELDS = SdkInternalSchemaSchemaMetadata::REQUIRED_FIELDS
        DECODERS = SdkInternalSchemaSchemaMetadata::DECODERS

        attr_reader :from, :reply_to
        # @return [Array_of_SchemaSchemaPersonalizationsItem] An array of messages and their metadata. Each object within the `personalizations` array can be thought of as a mail envelope—it defines who should receive an individual message and how that message should be handled. See **Personalizations** for more information.
        attr_reader :personalizations
        # @return [Array_of_MailTo] An array of recipients to whom replies will be sent. Each object in this array must contain a recipient's email address. Each object in the array may optionally contain a recipient's name. You can use either the `reply_to` property or `reply_to_list` property but not both.
        attr_reader :reply_to_list
        # @return [String] The global or _message level_ subject of your email. Subject lines set in personalizations objects will override this global subject line. See line length limits specified in RFC 2822 for guidance on subject line character limits.
        attr_reader :subject
        # @return [Array_of_SchemaSchemaContentItem] An array of objects, each containing a message body's content and MIME type. You must specify at least one MIME type and may include multiple. To include more than one MIME type, add an object for each type to the array.
        attr_reader :content
        # @return [Array_of_SchemaSchemaAttachmentsItem] An array of objects where you can define any attachments to be included with the message. Each object contains a `content` property, which must be a Base64 encoded string of the attachment itself, and `type`, `filename`, `disposition`, and `content_id` properties that tell SendGrid how to handle the attachment.
        attr_reader :attachments
        # @return [String] An email template ID. A template that contains a subject and content—either text or html—will override any subject and content values specified at the `personalizations` or message level. If a template ID begins with `d-`, it is a dynamic template and will work with the `dynamic_template_data` property. If the template ID does not begin with `d-`, it is a standard SendGrid template and will work with the `substitutions` property. See **How to Send an Email with Dynamic…
        attr_reader :template_id
        # @return [Hash] A collection of JSON property name and property value pairs allowing you to specify handling instructions for your email. You may not override the following headers: `x-sg-id`, `x-sg-eid`, `received`, `dkim-signature`, `Content-Type`, `Content-Transfer-Encoding`, `To`, `From`, `Subject`, `Reply-To`, `CC`, `BCC`.
        attr_reader :headers
        # @return [Array_of_String] An array of category names assigned to this message. Categories allow you to group messages by categories you define. Categories should be used sparingly to create general groups that are relevant to you. Categories are not meant to be used to track individual mail sends. For more granular categorization and tracking, use the `custom_args` property. A category name cannot exceed 255 characters. See **Working with Categories** for more information.
        attr_reader :categories
        # @return [String] Values that are specific to the entire send that will be carried along with the email and its activity data. Substitutions will not be made on custom arguments, so any string that is assigned to this property will be assumed to be the custom argument that you would like to be used. This parameter is overridden by `custom_args` set at the personalizations level. Total `custom_args` size may not exceed 10,000 bytes.
        attr_reader :custom_args
        # @return [Integer] A unix timestamp allowing you to specify when your email should be sent. A send cannot be scheduled more than 72 hours in advance. This property may be overridden by the `send_at` property set at the personalizations level.
        attr_reader :send_at
        # @return [String] An ID representing a batch of emails to be sent at the same time. Including a `batch_id` in your request allows you to include this email in that batch. It also enables you to cancel or pause the delivery of that batch. See the Scheduled Sends API for more information about scheduling your email.
        attr_reader :batch_id
        # @return [SchemaSchemaAsm] An object allowing you to specify how to handle unsubscribes. With SendGrid, an unsubscribe is the action an email recipient takes when they opt-out of receiving your messages. A suppression is the action you take as a sender to filter or suppress an unsubscribed address from your email send. From the perspective of the recipient, your suppression is the result of their unsubscribe. See **Suppression Groups** for more information.
        attr_reader :asm
        # @return [String] The IP Pool that you would like to send this email from. IP Pools allow you to group your dedicated Twilio SendGrid IP addresses in order to have more control over your deliverability. See **IP Pools** for more information.
        attr_reader :ip_pool_name
        # @return [SchemaSchemaMailSettings] A collection of different mail settings that you can use to specify how you would like this email to be handled. Mail settings provide extra functionality to your mail send. See **Mail Settings** for more information.
        attr_reader :mail_settings
        # @return [SchemaSchemaTrackingSettings] Settings to determine how you would like to track the metrics of how your recipients interact with your email. See **Tracking Settings** for more information.
        attr_reader :tracking_settings

        def initialize(**attributes)
          SdkModel.assign(self, attributes, FIELDS, REQUIRED_FIELDS)
          freeze
        end

        def self.from_hash(data)
          SdkModel.from_hash(self, data, FIELDS, REQUIRED_FIELDS, DECODERS)
        end

        def to_h
          SdkModel.to_h(self, FIELDS)
        end
      end

      # Submits an email for delivery through Twilio SendGrid. Provide `personalizations`, `from`, and message content, and use `template_id` when a stored template should supply the subject and content. A 202 response confirms that SendGrid accepted the message for processing.
      #
      # *The Mail Send operation allows you to send email over SendGrid's v3 Web API* For an overview of this API, including its features and limitations, please see the Mail Send API overview page The overview page also includes links to SendGrid's Email API quickstarts and helper libraries to get you working with this endpoint even faster.
      #
      # @param personalizations [Array_of_Hash] An array of messages and their
      #   metadata. Each object within the `personalizations` array can be thought of
      #   as a mail envelope—it defines who should receive an individual message and
      #   how that message should be handled. See **Personalizations** for more
      #   information.
      # @param content_encoding [ContentEncoding] Use this header when sending a
      #   gzip compressed mail body. Mail body compression is available to some high
      #   volume accounts. Submit a request to support to have gzip enabled on your
      #   account.
      # @param reply_to_list [Array_of_MailTo] An array of recipients to whom
      #   replies will be sent. Each object in this array must contain a recipient's
      #   email address. Each object in the array may optionally contain a recipient's
      #   name. You can use either the `reply_to` property or `reply_to_list` property
      #   but not both.
      # @param subject [String] The global or _message level_ subject of your email.
      #   Subject lines set in personalizations objects will override this global
      #   subject line. See line length limits specified in RFC 2822 for guidance on
      #   subject line character limits.
      # @param content [Array_of_Hash] An array of objects, each containing a
      #   message body's content and MIME type. You must specify at least one MIME
      #   type and may include multiple. To include more than one MIME type, add an
      #   object for each type to the array.
      # @param attachments [Array_of_Hash] An array of objects where you can define
      #   any attachments to be included with the message. Each object contains a
      #   `content` property, which must be a Base64 encoded string of the attachment
      #   itself, and `type`, `filename`, `disposition`, and `content_id` properties
      #   that tell SendGrid how to handle the attachment.
      # @param template_id [String] An email template ID. A template that contains a
      #   subject and content—either text or html—will override any subject and
      #   content values specified at the `personalizations` or message level. If a
      #   template ID begins with `d-`, it is a dynamic template and will work with
      #   the `dynamic_template_data` property. If the template ID does not begin with
      #   `d-`, it is a standard SendGrid template and will work with the
      #   `substitutions` property. See **How to Send an Email with Dynamic…
      # @param headers [Hash] A collection of JSON property name and property value
      #   pairs allowing you to specify handling instructions for your email. You may
      #   not override the following headers: `x-sg-id`, `x-sg-eid`, `received`,
      #   `dkim-signature`, `Content-Type`, `Content-Transfer-Encoding`, `To`, `From`,
      #   `Subject`, `Reply-To`, `CC`, `BCC`.
      # @param categories [Array_of_String] An array of category names assigned to
      #   this message. Categories allow you to group messages by categories you
      #   define. Categories should be used sparingly to create general groups that
      #   are relevant to you. Categories are not meant to be used to track individual
      #   mail sends. For more granular categorization and tracking, use the
      #   `custom_args` property. A category name cannot exceed 255 characters. See
      #   **Working with Categories** for more information.
      # @param custom_args [String] Values that are specific to the entire send that
      #   will be carried along with the email and its activity data. Substitutions
      #   will not be made on custom arguments, so any string that is assigned to this
      #   property will be assumed to be the custom argument that you would like to be
      #   used. This parameter is overridden by `custom_args` set at the
      #   personalizations level. Total `custom_args` size may not exceed 10,000
      #   bytes.
      # @param send_at [Integer] A unix timestamp allowing you to specify when your
      #   email should be sent. A send cannot be scheduled more than 72 hours in
      #   advance. This property may be overridden by the `send_at` property set at
      #   the personalizations level.
      # @param batch_id [String] An ID representing a batch of emails to be sent at
      #   the same time. Including a `batch_id` in your request allows you to include
      #   this email in that batch. It also enables you to cancel or pause the
      #   delivery of that batch. See the Scheduled Sends API for more information
      #   about scheduling your email.
      # @param asm [SchemaSchemaAsm] An object allowing you to specify how to handle
      #   unsubscribes. With SendGrid, an unsubscribe is the action an email recipient
      #   takes when they opt-out of receiving your messages. A suppression is the
      #   action you take as a sender to filter or suppress an unsubscribed address
      #   from your email send. From the perspective of the recipient, your
      #   suppression is the result of their unsubscribe. See **Suppression Groups**
      #   for more information.
      # @param ip_pool_name [String] The IP Pool that you would like to send this
      #   email from. IP Pools allow you to group your dedicated Twilio SendGrid IP
      #   addresses in order to have more control over your deliverability. See **IP
      #   Pools** for more information.
      # @param mail_settings [SchemaSchemaMailSettings] A collection of different
      #   mail settings that you can use to specify how you would like this email to
      #   be handled. Mail settings provide extra functionality to your mail send. See
      #   **Mail Settings** for more information.
      # @param tracking_settings [SchemaSchemaTrackingSettings] Settings to
      #   determine how you would like to track the metrics of how your recipients
      #   interact with your email. See **Tracking Settings** for more information.
      def self.send_mail(
        config:,
        personalizations:,
        from:,
        content_encoding: NOT_GIVEN,
        reply_to: NOT_GIVEN,
        reply_to_list: NOT_GIVEN,
        subject: NOT_GIVEN,
        content: NOT_GIVEN,
        attachments: NOT_GIVEN,
        template_id: NOT_GIVEN,
        headers: NOT_GIVEN,
        categories: NOT_GIVEN,
        custom_args: NOT_GIVEN,
        send_at: NOT_GIVEN,
        batch_id: NOT_GIVEN,
        asm: NOT_GIVEN,
        ip_pool_name: NOT_GIVEN,
        mail_settings: NOT_GIVEN,
        tracking_settings: NOT_GIVEN
      )

        Validation.validate_items('personalizations', personalizations, max: 1000)

        Validation.if_given(reply_to_list) do
          Validation.validate_items('reply_to_list', reply_to_list, max: 1000)
        end

        Validation.if_given(subject) { Validation.validate_length('subject', subject, min: 1) }

        Validation.if_given(categories) { Validation.validate_items('categories', categories, max: 10) }

        Validation.if_given(ip_pool_name) do
          Validation.validate_length('ip_pool_name', ip_pool_name, min: 2, max: 64)
        end

        SdkClient.request(
          'POST',
          "/v3/mail/send",
          config: config,
          body: {
            'personalizations' => personalizations,
            'from' => from,
            'reply_to' => reply_to,
            'reply_to_list' => reply_to_list,
            'subject' => subject,
            'content' => content,
            'attachments' => attachments,
            'template_id' => template_id,
            'headers' => headers,
            'categories' => categories,
            'custom_args' => custom_args,
            'send_at' => send_at,
            'batch_id' => batch_id,
            'asm' => asm,
            'ip_pool_name' => ip_pool_name,
            'mail_settings' => mail_settings,
            'tracking_settings' => tracking_settings,
          },
          decoder: :empty,
          operation_id: 'send_mail',
          extra_headers: SdkClient.serialize_headers({
            'Content-Encoding' => content_encoding,
          }),
        ).data
      end
    end
  end
end
