# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

require 'net/http'
require 'uri'
require 'json'
require 'securerandom'
require 'time'

# Defines the OctriSendGridMail SDK namespace.
module OctriSendGridMail
  # Shared model hydration and serialization primitives.
  module SdkModel
    module_function

    def assign(target, attributes, fields, required_fields)
      unknown_fields = attributes.keys - fields.keys
      missing_fields = required_fields - attributes.keys
      raise ArgumentError, "Unknown fields: #{unknown_fields.join(', ')}" unless unknown_fields.empty?
      raise ArgumentError, "Missing fields: #{missing_fields.join(', ')}" unless missing_fields.empty?

      fields.each_key do |field|
        target.instance_variable_set(:"@#{field}", attributes.fetch(field, NOT_GIVEN))
      end
    end

    def from_hash(model_class, data, fields, required_fields, decoders)
      return nil if data.nil?

      attributes = fields.to_h do |field, wire_name|
        [field, field_value(data, field, wire_name, required_fields, decoders)]
      end
      model_class.new(**attributes)
    end

    def field_value(data, field, wire_name, required_fields, decoders)
      return NOT_GIVEN unless data.key?(wire_name) || required_fields.include?(field)

      value = data.fetch(wire_name)
      decoder = decoders[field]
      decoder ? decoder.call(value) : value
    end

    def to_h(model, fields)
      fields.each_with_object({}) do |(field, wire_name), result|
        value = model.public_send(field)
        result[wire_name] = deep_to_h(value) unless value.equal?(NOT_GIVEN)
      end
    end

    def deep_to_h(value)
      case value
      when Array then value.map { |item| deep_to_h(item) }
      when Hash
        value.each_with_object({}) do |(key, item), result|
          result[key] = deep_to_h(item) unless item.equal?(NOT_GIVEN)
        end
      when NilClass, TrueClass, FalseClass, Integer, Float, String then value
      else
        value.class.const_defined?(:FIELDS, false) ? deep_to_h(value.to_h) : value
      end
    end
  end

  UploadFile = Struct.new(:data, :filename, :content_type, keyword_init: true) do
    def initialize(data:, filename:, content_type: 'application/octet-stream')
      super(data: data.b, filename: filename, content_type: content_type)
      freeze
    end
  end

  MultipartPart = Struct.new(:value, :content_type) do
    def initialize(value, content_type: 'application/json')
      super(value, content_type)
      freeze
    end
  end

  QueryValue = Struct.new(:value, :style, :explode) do
    def initialize(value, style: 'form', explode: true)
      super(value, style, explode)
      freeze
    end
  end

  # Incremental SSE parser. It retains only the unfinished line/event between
  # chunks and emits completed events immediately.
  class SseParser
    def initialize
      @buffer = +''
      reset_event
    end

    def feed(chunk)
      @buffer << chunk
      events = []
      while (newline = @buffer.index("\n"))
        event = consume_line(@buffer.slice!(0, newline + 1).chomp)
        events << event if event
      end
      events
    end

    def finish
      consume_line('')
    end

    private

    def consume_line(line)
      return flush if line.empty?
      return if line.start_with?(':')

      field, value = line.split(':', 2)
      value = value&.delete_prefix(' ') || ''
      @event_name = value if field == 'event'
      @data_lines << value if field == 'data'
      @event_id = value if field == 'id'
      @event_retry = value.to_i if field == 'retry'
      nil
    end

    def flush
      return if @data_lines.empty?

      event = SdkStreamEvent.new(
        event: @event_name || 'message',
        data: @data_lines.join("\n"),
        id: @event_id,
        retry: @event_retry
      )
      reset_event
      event
    end

    def reset_event
      @event_name = nil
      @event_id = nil
      @event_retry = nil
      @data_lines = []
    end
  end

  # Single execution path for every generated method. Returns a typed
  # SdkResponse on 2xx; raises SdkHttpError, SdkNetworkError, or
  # SdkTimeoutError otherwise.
  module SdkClient
    REQ_CLASS = {
      'GET' => Net::HTTP::Get,
      'POST' => Net::HTTP::Post,
      'PUT' => Net::HTTP::Put,
      'PATCH' => Net::HTTP::Patch,
      'DELETE' => Net::HTTP::Delete
    }.freeze

    IDEMPOTENT_METHODS = %w[GET HEAD PUT DELETE OPTIONS].freeze
    ALWAYS_RETRYABLE_STATUSES = [429, 503].freeze
    REQUEST_ID_HEADERS = %w[x-request-id openai-request-id x-amzn-requestid].freeze
    PII_KEYS = %w[authorization cookie set_cookie setcookie password passcode secret token api_key apikey access_token accesstoken refresh_token refreshtoken client_secret clientsecret email email_address emailaddress phone phone_number phonenumber address street_address streetaddress street city postal_code postalcode zip_code zipcode first_name firstname last_name lastname full_name fullname username user_name ip ip_address ipaddress user_agent useragent referrer url uri query latitude longitude ssn social_security_number socialsecuritynumber tax_id taxid national_id nationalid passport_number passportnumber date_of_birth dateofbirth birth_date birthdate headers body request_headers requestheaders request_body requestbody].freeze
    PII_REDACTION_MARKER = '[REDACTED]'

    def self.normalize_pii_key(key)
      key.to_s.downcase.tr('- ', '__')
    end

    # Recursively redacts common credential and direct-identifier fields.
    def self.sanitize_telemetry(value, enabled)
      return value unless enabled

      case value
      when Array
        value.map { |item| sanitize_telemetry(item, enabled) }
      when Hash
        value.each_with_object({}) do |(key, item), output|
          output[key] = PII_KEYS.include?(normalize_pii_key(key)) ? PII_REDACTION_MARKER : sanitize_telemetry(item, enabled)
        end
      else
        value
      end
    end

    # Recursively converts nested SDK objects to plain Ruby hashes/arrays
    # suitable for JSON serialization.
    def self.deep_to_h(val)
      case val
      when Array then val.map { |v| deep_to_h(v) }
      when Hash
        val.each_with_object({}) do |(key, value), result|
          result[key] = deep_to_h(value) unless value.equal?(NOT_GIVEN)
        end
      when NilClass, TrueClass, FalseClass, Integer, Float, String then val
      else val.respond_to?(:to_h) ? deep_to_h(val.to_h) : val
      end
    end

    def self.q(**pairs)
      pairs
    end

    # @return [SdkResponse]
    # What a request asks for when the operation does not decode JSON. A server
    # that honours Accept answers a bare `application/json` with the JSON variant
    # of an endpoint whose bytes the SDK is downloading — OpenAI's skill bundle
    # arrived as a quoted JSON string instead of a zip.
    ACCEPT_BY_DECODER = { bytes: '*/*', text: '*/*' }.freeze

    def self.request(method, path, config: nil, query: nil, body: NOT_GIVEN, content_type: 'application/json', return_type: nil, decoder: :json, operation_id: '', extra_headers: nil)
      accept = ACCEPT_BY_DECODER[decoder]
      extra_headers = { 'Accept' => accept }.merge(extra_headers || {}) if accept
      cfg, upper_method, url, auth_headers, body_string, content_type = prepare_request(
        method,
        path,
        config: config,
        query: query,
        body: body,
        content_type: content_type
      )
      retry_cfg = cfg.retry || RetryConfig.new
      idem = cfg.idempotency || IdempotencyConfig.new
      idempotency_key = SecureRandom.uuid if idem.enabled && idem.methods.include?(upper_method)
      terminal = ->(req) { core_transport(req, cfg.timeout) }
      dispatch = compose_middleware(cfg.middleware || [], terminal)

      dispatch_with_retries(
        config: cfg, method: upper_method, path: path, url: url,
        auth_headers: auth_headers, body: body, body_string: body_string,
        content_type: content_type, operation_id: operation_id,
        extra_headers: extra_headers, retry_config: retry_cfg,
        idempotency_config: idem, idempotency_key: idempotency_key,
        dispatch: dispatch, decoder: decoder, return_type: return_type
      )
    end

    def self.dispatch_with_retries(config:, method:, path:, url:, auth_headers:, body:, body_string:, content_type:,
                                   operation_id:, extra_headers:, retry_config:, idempotency_config:, idempotency_key:,
                                   dispatch:, decoder:, return_type:)
      attempt = 0
      while attempt < retry_config.max_attempts
        attempt += 1
        begin
          raw = dispatch_attempt(
            config: config, method: method, url: url, auth_headers: auth_headers,
            body_present: !body.equal?(NOT_GIVEN), body_string: body_string,
            content_type: content_type, operation_id: operation_id, attempt: attempt,
            extra_headers: extra_headers, idempotency_config: idempotency_config,
            idempotency_key: idempotency_key, dispatch: dispatch
          )
        rescue SdkTimeoutError, SdkNetworkError => e
          raise log_error(config, method, path, operation_id, e) if attempt >= retry_config.max_attempts

          sleep_backoff(retry_config, attempt, nil)
          next
        end

        envelope = successful_response(raw, config, decoder, return_type)
        return envelope if envelope

        if attempt < retry_config.max_attempts && retry_status?(method, raw.status_code, retry_config.retry_on)
          sleep_backoff(retry_config, attempt, raw.headers['retry-after'])
          next
        end

        raise log_error(config, method, path, operation_id, http_error(raw))
      end

      # Reachable only if max_attempts is misconfigured to 0.
      raise log_error(config, method, path, operation_id,
                      SdkNetworkError.new(RuntimeError.new("Request '#{operation_id}' produced no attempts")))
    end

    def self.dispatch_attempt(config:, method:, url:, auth_headers:, body_present:, body_string:, content_type:, operation_id:, attempt:, extra_headers:, idempotency_config:, idempotency_key:, dispatch:)
      # Auth headers are rebuilt per attempt for OAuth refresh tolerance.
      headers = build_headers(config, auth_headers, content_type, body_present)
      headers.merge!(extra_headers) if extra_headers
      headers[idempotency_config.header_name] = idempotency_key if idempotency_key
      request = SdkRequest.new(
        method: method, url: url, headers: headers, body: body_string,
        content_type: content_type, operation_id: operation_id, attempt: attempt
      )
      execute_attempt(dispatch, request, config.timeout)
    end

    # The error body is DECODED, matching the other SDKs: a JSON error payload
    # reaches the caller as a Hash so `error.body['message']` works everywhere.
    # A non-JSON body is handed back verbatim.
    def self.http_error(raw)
      SdkHttpError.new(
        status_code: raw.status_code, status_text: raw.status_text,
        body: decode_error_body(raw.body, raw.headers), headers: raw.headers,
        request_id: raw.request_id
      )
    end

    def self.decode_error_body(body, headers)
      return body unless body.is_a?(String) && !body.empty?

      content_type = headers.is_a?(Hash) ? headers.find { |name, _| name.to_s.downcase == 'content-type' }&.last.to_s : ''
      return body unless content_type.include?('json') || body.start_with?('{', '[')

      begin
        JSON.parse(body)
      rescue JSON::ParserError
        body
      end
    end

    def self.execute_attempt(dispatch, request, timeout)
      dispatch.call(request)
    rescue Timeout::Error
      raise SdkTimeoutError, timeout
    rescue SdkTimeoutError, SdkNetworkError
      raise
    rescue StandardError => e
      raise SdkNetworkError, e
    end

    def self.successful_response(raw, config, decoder, return_type)
      return nil unless raw.status_code.between?(200, 299)

      envelope = SdkResponse.new(
        data: decode_body(raw.body, decoder, return_type),
        status_code: raw.status_code,
        headers: raw.headers,
        request_id: raw.request_id,
        latency: raw.latency,
        attempt: raw.attempt
      )
      config.on_response&.call(envelope)
      envelope
    end

    # Fires the error logger (when configured) and returns the error unchanged so
    # terminal failures can be wrapped inline at each raise site. Delivery is
    # fire-and-forget on a background thread; a logging failure never masks the
    # originating error. eventId lets the backend deduplicate retried deliveries.
    def self.log_error(cfg, method, path, operation_id, error)
      logging = cfg.logging
      return error unless logging&.enabled && logging.endpoint

      payload = build_log_payload(logging, method, path, operation_id, error)
      Thread.new { deliver_log(logging, payload) }
      error
    end

    def self.build_log_payload(logging, method, path, operation_id, error)
      payload = {
        eventId: SecureRandom.uuid,
        timestamp: Time.now.utc.iso8601,
        level: 'error',
        operationId: operation_id,
        method: method,
        path: path,
        error: log_error_object(error)
      }
      {
        statusCode: error.status_code,
        requestId: error.request_id,
        environment: logging.environment,
        release: logging.release,
        user: logging.user,
        tags: logging.tags
      }.each { |key, value| payload[key] = value unless value.nil? }
      payload
    end

    def self.log_error_object(error)
      result = {
        name: error.class.name.split('::').last,
        message: error.message,
        stack: (error.backtrace || caller).join("\n")
      }
      frames = build_frames(error)
      result[:frames] = frames unless frames.empty?
      result
    end

    def self.deliver_log(logging, payload)
      endpoint = logging.endpoint
      api_key = logging.api_key
      uri = URI(endpoint)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      http.open_timeout = 2
      http.read_timeout = 2
      req = Net::HTTP::Post.new(uri)
      req['Content-Type'] = 'application/json'
      req['Authorization'] = "Bearer #{api_key}" if api_key
      req.body = JSON.generate(sanitize_telemetry(payload, logging.filter_pii))
      http.request(req)
    rescue StandardError
      # Logging failures must never mask the originating error.
    end

    # Reads a few source lines around a frame so the dashboard can show the
    # original code for languages that are not minified (no source maps needed).
    def self.source_context(path, lineno)
      return {} if path.nil? || lineno.nil? || lineno < 1

      begin
        lines = File.readlines(path)
      rescue StandardError
        return {}
      end
      return {} if lines.empty? || lineno > lines.length

      idx = lineno - 1
      ctx = { contextLine: lines[idx].chomp }
      pre = lines[[0, idx - 5].max...idx].map(&:chomp)
      post = lines[(idx + 1)...(idx + 6)].map(&:chomp)
      ctx[:preContext] = pre unless pre.empty?
      ctx[:postContext] = post unless post.empty?
      ctx
    end

    # A frame is in-app unless it lives in an installed gem or the Ruby stdlib.
    def self.frame_in_app?(path)
      return false if path.nil? || path.empty?

      !path.include?('/gems/') && !path.include?('/ruby/') && !path.start_with?('<')
    end

    # Structured stack frames with original-source context, innermost first.
    def self.build_frames(error)
      locations = error.backtrace_locations
      return [] if locations.nil?

      locations.map do |loc|
        path = loc.absolute_path || loc.path
        {
          function: loc.label,
          filename: path,
          lineno: loc.lineno,
          inApp: frame_in_app?(path)
        }.merge(source_context(path, loc.lineno))
      end
    end

    # Composes a middleware stack around the terminal handler. The first
    # middleware in `stack` is the outermost. Returns `terminal` when empty.
    def self.compose_middleware(stack, terminal)
      return terminal if stack.nil? || stack.empty?

      next_in_chain = terminal
      stack.reverse_each do |mw|
        captured = next_in_chain
        next_in_chain = ->(req) { mw.call(req, captured) }
      end
      next_in_chain
    end

    # Innermost handler: performs the actual Net::HTTP exchange and assembles
    # an SdkRawResponse. Non-2xx is returned as-is so middleware can inspect.
    def self.core_transport(sdk_req, timeout)
      started = Time.now
      uri = URI.parse(sdk_req.url)
      response = dispatch_request(uri, sdk_req.method, sdk_req.headers, sdk_req.body, timeout)
      resp_headers = flatten_headers(response)
      SdkRawResponse.new(
        status_code: response.code.to_i,
        status_text: response.message.to_s,
        headers: resp_headers,
        body: response.body.to_s,
        request_id: find_request_id(resp_headers),
        latency: Time.now - started,
        attempt: sdk_req.attempt
      )
    end

    def self.dispatch_request(uri, method, headers, body, timeout)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      http.open_timeout = timeout
      http.read_timeout = timeout

      klass = REQ_CLASS[method] or raise ArgumentError, "Unsupported HTTP method: #{method}"
      req = klass.new(uri.request_uri)
      req['Accept'] = 'application/json'
      headers.each { |k, v| req[k.to_s] = v }
      req.body = body if body
      http.request(req)
    end

    def self.build_query_string(params = nil, has_query: false, **keyword_params)
      params ||= keyword_params
      pairs = []
      params.each do |key, raw|
        query_value = raw.is_a?(QueryValue) ? raw : QueryValue.new(raw)
        value = query_value.value
        next if value.nil? || value.equal?(NOT_GIVEN)

        if value.is_a?(Array)
          delimiter = { 'spaceDelimited' => ' ', 'pipeDelimited' => '|' }.fetch(query_value.style, ',')
          values = query_value.style == 'form' && query_value.explode ? value : [value.join(delimiter)]
          values.each { |item| pairs << [key.to_s, item.to_s] }
        else
          pairs << [key.to_s, value.to_s]
        end
      end
      return '' if pairs.empty?

      separator = has_query ? '&' : '?'
      separator + URI.encode_www_form(pairs)
    end

    def self.encode_path_segment(value)
      URI::DEFAULT_PARSER.escape(value.to_s, /[^A-Za-z0-9\-._~]/)
    end

    def self.prepare_request(method, path, config:, query:, body:, content_type:)
      cfg = config || SdkConfig.config
      upper_method = method.to_s.upcase
      auth_headers, auth_query = resolve_auth(cfg)
      merged_query = auth_query.empty? ? query : (query || {}).merge(auth_query)
      url = "#{cfg.base_url.to_s.chomp('/')}#{path}"
      url += build_query_string(merged_query, has_query: path.include?('?')) if merged_query && !merged_query.empty?
      body_string, content_type = prepare_body(body, content_type)
      [cfg, upper_method, url, auth_headers, body_string, content_type]
    end

    def self.prepare_body(body, content_type)
      return [encode_body(body, content_type), content_type] unless content_type.start_with?('multipart/form-data') && body.is_a?(Hash)

      boundary = "----InterfacerFormBoundary#{rand(36**24).to_s(36)}"
      [encode_multipart(body, boundary), "multipart/form-data; boundary=#{boundary}"]
    end

    def self.serialize_headers(values)
      values.each_with_object({}) do |(key, value), result|
        next if value.nil? || value.equal?(NOT_GIVEN)

        result[key.to_s] = value.to_s
      end
    end

    def self.build_headers(config, auth_headers, content_type, has_body)
      headers = {}
      auth = config.auth
      auth&.headers&.each { |k, v| headers[k.to_s] = v }
      auth_headers.each { |k, v| headers[k.to_s] = v }
      headers['Content-Type'] = content_type if has_body
      headers
    end

    # Resolves all configured auth into [headers, query_params]. OAuth2 fetch
    # happens here, before the retry loop starts.
    def self.resolve_auth(config)
      headers = {}
      query = {}
      auth = config.auth
      return [headers, query] unless auth

      headers['Authorization'] = "Bearer #{auth.bearer}" if auth.bearer

      headers['Authorization'] = "Bearer #{auth.bearer_auth}" if auth.bearer_auth

      [headers, query]
    end

    def self.encode_body(body, content_type)
      return nil if body.equal?(NOT_GIVEN)
      return JSON.generate(deep_to_h(body)) if content_type.include?('json')
      return '' if body.nil?

      body.to_s
    end

    # Builds schema-aware multipart data with repeated uploads and metadata.
    def self.encode_multipart(fields, boundary)
      out = String.new(encoding: Encoding::ASCII_8BIT)
      multipart_entries(fields).each do |key, value, content_type|
        append_multipart_part(out, boundary, key, value, content_type)
      end
      out << "--#{boundary}--\r\n".b
      out
    end

    def self.multipart_entries(fields)
      fields.flat_map do |key, raw|
        case raw
        when MultipartPart
          raw.value.equal?(NOT_GIVEN) ? [] : [[key, raw.value, raw.content_type]]
        when Array
          raw.flat_map { |item| multipart_entries(key => item) }
        else
          raw.equal?(NOT_GIVEN) ? [] : [[key, raw, nil]]
        end
      end
    end

    def self.append_multipart_part(out, boundary, key, value, content_type)
      disposition = %(Content-Disposition: form-data; name="#{escape_multipart_token(key)}")
      if value.is_a?(UploadFile)
        disposition << %(; filename="#{escape_multipart_token(value.filename)}")
        content_type = value.content_type
        payload = value.data
      elsif multipart_json_value?(value, content_type)
        content_type ||= 'application/json'
        payload = JSON.generate(deep_to_h(value)).b
      else
        payload = value.nil? ? 'null'.b : value.to_s.b
      end
      out << "--#{boundary}\r\n#{disposition}\r\n".b
      out << "Content-Type: #{content_type}\r\n".b if content_type
      out << "\r\n".b << payload << "\r\n".b
    end

    def self.escape_multipart_token(value)
      value.to_s.gsub(/["\\]/) { |char| "\\#{char}" }
    end

    def self.multipart_json_value?(value, content_type)
      return true if content_type || value.is_a?(Hash)
      return false if value.nil?

      scalar_types = [String, Integer, Float, TrueClass, FalseClass]
      scalar_types.none? { |type| value.is_a?(type) }
    end

    def self.flatten_headers(response)
      out = {}
      response.each_header { |name, value| out[name.downcase] = value }
      out
    end

    def self.find_request_id(headers)
      REQUEST_ID_HEADERS.each { |name| return headers[name] if headers[name] }
      nil
    end

    def self.retry_status?(method, status, retry_on)
      return false unless retry_on.include?(status)
      return true if IDEMPOTENT_METHODS.include?(method)

      ALWAYS_RETRYABLE_STATUSES.include?(status)
    end

    def self.sleep_backoff(retry_cfg, attempt, retry_after)
      max_sec = retry_cfg.max_backoff
      wait =
        if retry_after.to_s.match?(/\A\d+\z/)
          [retry_after.to_i, max_sec].min
        else
          exp = retry_cfg.backoff * (2**(attempt - 1))
          jitter = rand * retry_cfg.backoff
          [exp + jitter, max_sec].min
        end
      sleep(wait) if wait.positive?
    end

    def self.decode_body(text, decoder, return_type)
      return nil if decoder == :empty
      return text.b if decoder == :bytes
      return text.dup.force_encoding(Encoding::UTF_8) if decoder == :text

      data = JSON.parse(text)
      decode_typed(data, return_type)
    end

    def self.decode_typed(data, return_type)
      return data if return_type.nil?

      if return_type.is_a?(Array)
        return data unless data.is_a?(Array)

        item_type = return_type.first
        return data.map { |item| decode_typed(item, item_type) }
      end
      return_type.respond_to?(:from_hash) ? return_type.from_hash(data) : data
    end

    # Opens an SSE connection and yields parsed events. Bypasses the retry
    # loop and idempotency layer — streaming connections are long-lived;
    # reconnect is the caller's responsibility. Returns an Enumerator when
    # called without a block, so callers can use .lazy / .first / .each.
    #
    # @yield [SdkStreamEvent]
    # @return [Enumerator] when no block is given
    def self.stream(method, path, config: nil, query: nil, body: NOT_GIVEN, content_type: 'application/json', operation_id: '', stream_format: :sse, stream_media_type: 'text/event-stream', chunk_domain: :bytes, extra_headers: nil, &block)
      return enum_for(:stream, method, path, config: config, query: query, body: body, content_type: content_type, operation_id: operation_id, stream_format: stream_format, stream_media_type: stream_media_type, chunk_domain: chunk_domain, extra_headers: extra_headers) unless block_given?

      cfg, upper_method, url, auth_headers, body_string, content_type = prepare_request(
        method,
        path,
        config: config,
        query: query,
        body: body,
        content_type: content_type
      )

      headers = build_headers(cfg, auth_headers, content_type, !body.equal?(NOT_GIVEN))
      headers.merge!(extra_headers) if extra_headers
      headers['Accept'] = stream_media_type

      http, request = build_http_request(
        upper_method,
        url,
        config: cfg,
        headers: headers,
        body_string: body_string
      )
      http.request(request) do |response|
        consume_stream_response(response, stream_format, chunk_domain, &block)
      end
    end

    def self.build_http_request(method, url, config:, headers:, body_string:)
      uri = URI.parse(url)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      http.open_timeout = config.timeout
      http.read_timeout = config.timeout

      klass = REQ_CLASS[method] or raise ArgumentError, "Unsupported HTTP method: #{method}"
      req = klass.new(uri.request_uri)
      headers.each { |k, v| req[k.to_s] = v }
      req.body = body_string if body_string
      [http, req]
    end

    def self.consume_stream_response(response, stream_format, chunk_domain, &block)
      raise_stream_error(response) unless response.code.to_i.between?(200, 299)

      if stream_format == :chunked
        response.read_body do |chunk|
          data = chunk_domain == :text ? chunk.dup.force_encoding(Encoding::UTF_8) : chunk.b
          block.call(SdkStreamEvent.new(event: 'chunk', data: data))
        end
        return
      end

      if stream_format == :ndjson
        buffer = +''
        response.read_body do |chunk|
          buffer << chunk
          while (newline = buffer.index("\n"))
            line = buffer.slice!(0, newline + 1).strip
            block.call(SdkStreamEvent.new(data: line)) unless line.empty?
          end
        end
        line = buffer.strip
        block.call(SdkStreamEvent.new(data: line)) unless line.empty?
        return
      end

      parser = SseParser.new
      response.read_body do |chunk|
        parser.feed(chunk).each { |event| block.call(event) }
      end
      event = parser.finish
      block.call(event) if event
    end

    def self.raise_stream_error(response)
      response_body = String.new
      response.read_body { |chunk| response_body << chunk }
      response_headers = flatten_headers(response)
      raise SdkHttpError.new(
        status_code: response.code.to_i,
        status_text: response.message.to_s,
        body: response_body,
        headers: response_headers,
        request_id: find_request_id(response_headers)
      )
    end

    # Polls a long-running operation until terminal. is_terminal returns
    # [done, failed, reason]. Raises SdkTimeoutError on deadline.
    def self.wait_for(poll, is_terminal, config: nil)
      cfg = config || WaitForConfig.new
      deadline = Time.now + cfg.timeout
      interval = cfg.interval
      loop do
        result = poll.call
        done, failed, reason = is_terminal.call(result)
        if done
          raise SdkNetworkError, RuntimeError.new("operation failed: #{reason || 'unknown'}") if failed

          return result
        end
        raise SdkTimeoutError, cfg.timeout if Time.now >= deadline

        jitter = rand * cfg.interval
        wait = [interval + jitter, cfg.max_interval].min
        sleep(wait)
        interval = [interval * 2, cfg.max_interval].min
      end
    end
  end

  # One Server-Sent Event yielded by SdkClient.stream. @data is the raw event
  # payload; consumers can JSON-decode it themselves when applicable.
  class SdkStreamEvent
    attr_accessor :event, :data, :id, :retry

    def initialize(event: 'message', data: '', id: nil, retry: nil)
      @event = event
      @data = data
      @id = id
      @retry = binding.local_variable_get(:retry)
    end
  end

  # Configuration for SdkClient.wait_for.
  class WaitForConfig
    attr_accessor :interval, :max_interval, :timeout

    def initialize(interval: 1.0, max_interval: 30.0, timeout: 600.0)
      @interval = interval
      @max_interval = max_interval
      @timeout = timeout
    end
  end
end
