# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

# Defines the OctriSendGridMail SDK namespace.
module OctriSendGridMail
  NOT_GIVEN = Object.new.freeze

  # Defines the ClientAuthConfig SDK type.
  class ClientAuthConfig
    attr_accessor :bearer, :bearer_auth, :headers

    def initialize
      @bearer = nil
      @bearer_auth = nil
      @headers = nil
    end
  end

  # Error reporting. The endpoint/key/environment below are baked in from the
  # dashboard monitoring config, but @enabled is false at rest — this SDK reports
  # nothing until the consumer opts in, either by configuring a ClientConfig whose
  # logging is enabled, or by calling Config.set_logging_config.
  class LoggingConfig
    attr_accessor :enabled, :endpoint, :api_key, :environment, :release, :user, :tags, :filter_pii

    def initialize
      @enabled = false
      @endpoint = nil
      @api_key = nil
      # Enrichment forwarded with every logged event.
      @environment = nil
      @release = nil
      @user = nil
      @tags = nil
      @filter_pii = true
    end
  end

  # Defines the RetryConfig SDK type.
  class RetryConfig
    attr_accessor :max_attempts, :retry_on, :backoff, :max_backoff

    def initialize
      @max_attempts = 3
      @retry_on = [408, 425, 429, 500, 502, 503, 504]
      @backoff = 0.5
      @max_backoff = 8.0
    end
  end

  # Controls Idempotency-Key generation, so a retried write is not executed twice.
  class IdempotencyConfig
    attr_accessor :enabled, :header_name, :methods

    def initialize
      @enabled = false
      @header_name = "Idempotency-Key"
      @methods = %w[POST PATCH]
    end
  end

  # A single in-flight HTTP attempt as seen by middleware. Mutating @headers
  # or @body alters the request before it hits the wire. @meta is a free-form
  # hash middleware can use to share state across the chain.
  class SdkRequest
    attr_accessor :method, :url, :headers, :body, :content_type, :operation_id, :attempt, :meta

    def initialize(method:, url:, headers: {}, body: nil, content_type: "application/json", operation_id: "", attempt: 1)
      @method = method
      @url = url
      @headers = headers
      @body = body
      @content_type = content_type
      @operation_id = operation_id
      @attempt = attempt
      @meta = {}
    end
  end

  # Raw response visible to middleware. @body is the undecoded response text.
  class SdkRawResponse
    attr_accessor :status_code, :status_text, :headers, :body, :request_id, :latency, :attempt

    def initialize(status_code:, status_text:, headers:, body:, request_id:, latency:, attempt:)
      @status_code = status_code
      @status_text = status_text
      @headers = headers
      @body = body
      @request_id = request_id
      @latency = latency
      @attempt = attempt
    end
  end

  # Defines the ClientConfig SDK type.
  class ClientConfig
    attr_accessor :base_url, :auth, :logging, :retry, :idempotency, :timeout, :on_response, :middleware

    def initialize
      @base_url = "https://api.sendgrid.com"
      @auth = nil
      @logging = LoggingConfig.new
      @retry = RetryConfig.new
      @idempotency = IdempotencyConfig.new
      @timeout = 30.0
      @on_response = nil
      # Middleware list — each entry is a proc accepting (sdk_req, next_proc)
      # and returning an SdkRawResponse. Replaced wholesale on configure();
      # to extend, read the current list and pass a new array.
      @middleware = []
    end
  end

  # Thread-safe global SDK configuration singleton.
  class SdkConfig
    @config = nil
    @mutex = Mutex.new

    class << self
      def configure(config)
        @mutex.synchronize { @config = config }
      end

      def config
        @mutex.synchronize do
          @config = ClientConfig.new if @config.nil?
          @config
        end
      end

      # Turns SDK logging on and configures it in one call.
      #
      # Logging is OFF by default — this SDK reports nothing until you ask it to.
      # There are exactly two ways to turn it on:
      #
      #   cfg = ClientConfig.new
      #   cfg.logging.enabled = true
      #   SdkConfig.configure(cfg)                      # at init
      #
      #   SdkConfig.set_logging_config                  # any time after
      #   SdkConfig.set_logging_config(environment: "production")
      #
      # The reporting endpoint is already baked in, so a bare call is enough.
      # Pass enabled: false to turn logging back off.
      def set_logging_config(**fields)
        config = self.config
        @mutex.synchronize do
          logging = config.logging ||= LoggingConfig.new
          # Opting in IS the point of this call, so enabled flips to true — the
          # keyword loop below runs after, so an explicit enabled: false wins.
          logging.enabled = true
          fields.each do |key, value|
            setter = :"#{key}="
            raise ArgumentError, "LoggingConfig has no field #{key}" unless logging.respond_to?(setter)

            logging.public_send(setter, value)
          end
          logging
        end
      end
    end
  end
end
