# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

# Defines the OctriSendGridMail SDK namespace.
module OctriSendGridMail
  # Envelope returned by the low-level request layer. High-level endpoint
  # methods unwrap +data+ automatically.
  class SdkResponse
    attr_reader :data, :status_code, :headers, :request_id, :latency, :attempt

    def initialize(data:, status_code:, headers:, request_id:, latency:, attempt:)
      @data = data
      @status_code = status_code
      @headers = headers
      @request_id = request_id
      @latency = latency
      @attempt = attempt
    end
  end

  # Top-level error type for every SDK failure path. Concrete subclasses:
  # SdkValidationError, SdkHttpError, SdkNetworkError, SdkTimeoutError.
  class SdkError < StandardError
    # @return [Integer, nil] HTTP status code when produced from an HTTP response.
    def status_code
      nil
    end

    # @return [String, nil] Request id captured from the HTTP response, if any.
    def request_id
      nil
    end
  end

  # Raised when a method argument fails an OpenAPI constraint pre-flight.
  class SdkValidationError < SdkError
    attr_reader :field, :code, :meta

    def initialize(field, code, message, meta = {})
      super(message)
      @field = field
      @code = code
      @meta = meta
    end
  end

  # Raised for any non-2xx HTTP response.
  class SdkHttpError < SdkError
    attr_reader :status_code, :status_text, :body, :headers, :request_id

    def initialize(status_code:, status_text:, body:, headers:, request_id: nil)
      super("HTTP #{status_code} #{status_text}")
      @status_code = status_code
      @status_text = status_text
      @body = body
      @headers = headers
      @request_id = request_id
    end
  end

  # Raised for connection / DNS / socket failures.
  class SdkNetworkError < SdkError
    attr_reader :cause, :request_id

    def initialize(cause, request_id: nil)
      super(cause.respond_to?(:message) ? cause.message : cause.to_s)
      @cause = cause
      @request_id = request_id
    end
  end

  # Raised when a request exceeds its configured timeout.
  class SdkTimeoutError < SdkError
    attr_reader :elapsed, :request_id

    def initialize(elapsed, request_id: nil)
      super("Request timed out after #{elapsed}s")
      @elapsed = elapsed
      @request_id = request_id
    end
  end
end
