# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

# Auto-generated SDK client
require_relative 'config'
require_relative 'types'
require_relative 'methods/mail_batch'
require_relative 'methods/mail_send'

# Defines the OctriSendGridMail SDK namespace.
module OctriSendGridMail
  SchemaSchemaAsm = Methods::MailSend::SchemaSchemaAsm
  SchemaSchemaMailSettings = Methods::MailSend::SchemaSchemaMailSettings
  SchemaSchemaTrackingSettings = Methods::MailSend::SchemaSchemaTrackingSettings
  SchemaSchema = Methods::MailSend::SchemaSchema
  # Defines the MailBatchNamespace SDK type.
  class MailBatchNamespace
    def initialize(config)
      @config = config
    end

    # **This operation allows you to generate a new mail batch ID.** Once a batch ID is created, you can associate it with a mail send by passing it in the request body of the Mail Send operation. This makes it possible to group multiple requests to the Mail Send operation by assigning them the same batch ID. A batch ID that's associated with a mail send can be used to access and modify the associated send. For example, you can pause or cancel a send using its batch ID. See the…
    def create(
      on_behalf_of: NOT_GIVEN
    )
      OctriSendGridMail::Methods::MailBatch.create_mail_batch(config: @config, on_behalf_of: on_behalf_of)
    end

    # **This operation allows you to validate a mail batch ID.** If you provide a valid batch ID, this operation will return a `200` status code and the batch ID itself. If you provide an invalid batch ID, you will receive a `400` level status code and an error message. A batch ID does not need to be assigned to a send to be considered valid. A successful response means only that the batch ID has been created, but it does not indicate that the ID has been assigned to a send.
    def get(
      batch_id:,
      on_behalf_of: NOT_GIVEN
    )
      OctriSendGridMail::Methods::MailBatch.get_mail_batch(config: @config, batch_id: batch_id, on_behalf_of: on_behalf_of)
    end
  end

  # Defines the MailSendNamespace SDK type.
  class MailSendNamespace
    def initialize(config)
      @config = config
    end

    # Submits an email for delivery through Twilio SendGrid. Provide `personalizations`, `from`, and message content, and use `template_id` when a stored template should supply the subject and content. A 202 response confirms that SendGrid accepted the message for processing.
    #
    # *The Mail Send operation allows you to send email over SendGrid's v3 Web API* For an overview of this API, including its features and limitations, please see the Mail Send API overview page The overview page also includes links to SendGrid's Email API quickstarts and helper libraries to get you working with this endpoint even faster.
    def send_mail(
      personalizations:,
      from:,
      content_encoding: NOT_GIVEN,
      reply_to: NOT_GIVEN,
      reply_to_list: NOT_GIVEN,
      subject: NOT_GIVEN,
      content: NOT_GIVEN,
      attachments: NOT_GIVEN,
      template_id: NOT_GIVEN,
      headers: NOT_GIVEN,
      categories: NOT_GIVEN,
      custom_args: NOT_GIVEN,
      send_at: NOT_GIVEN,
      batch_id: NOT_GIVEN,
      asm: NOT_GIVEN,
      ip_pool_name: NOT_GIVEN,
      mail_settings: NOT_GIVEN,
      tracking_settings: NOT_GIVEN
    )
      OctriSendGridMail::Methods::MailSend.send_mail(config: @config, personalizations: personalizations, from: from, content_encoding: content_encoding, reply_to: reply_to, reply_to_list: reply_to_list, subject: subject, content: content, attachments: attachments, template_id: template_id, headers: headers, categories: categories, custom_args: custom_args, send_at: send_at, batch_id: batch_id, asm: asm, ip_pool_name: ip_pool_name, mail_settings: mail_settings, tracking_settings: tracking_settings)
    end
  end

  # Defines the TwilioSendGridMail SDK type.
  class TwilioSendGridMail
    attr_reader :mail_batch, :mail_send

    def initialize(config)
      @config = config
      @mail_batch = MailBatchNamespace.new(config)
      @mail_send = MailSendNamespace.new(config)
    end

    # Turns SDK logging on and configures it. Logging is OFF by default — this
    # SDK reports nothing until you call this (or construct the client with a
    # config whose logging is enabled). The reporting endpoint is already baked
    # in, so a bare call is enough. Pass enabled: false to turn logging back off.
    def set_logging_config(**fields)
      logging = (@config.logging ||= LoggingConfig.new)
      # Opting in IS the point of this call, so enabled flips to true — the
      # keyword loop below runs after, so an explicit enabled: false wins.
      logging.enabled = true
      fields.each do |key, value|
        setter = :"#{key}="
        raise ArgumentError, "LoggingConfig has no field #{key}" unless logging.respond_to?(setter)

        logging.public_send(setter, value)
      end
      logging
    end
  end
end
