# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

# Auto-generated model index
module OctriSendGridMail
end
require_relative 'models/mail_batch'
require_relative 'models/mail_send'
require_relative 'models/shared'
