# frozen_string_literal: true

# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

require 'uri'

# Defines the OctriSendGridMail SDK namespace.
module OctriSendGridMail
  # Defines the Validation SDK namespace.
  module Validation
    def self.if_given(value)
      return if value.equal?(NOT_GIVEN) || value.nil?

      yield
    end

    def self.validate_length(field, value, min: nil, max: nil)
      n = value.length
      if min && n < min
        raise SdkValidationError.new(field, 'length',
                                     "Validation failed for '#{field}': length must be >= #{min}")
      end
      return unless max && n > max

      raise SdkValidationError.new(field, 'length',
                                   "Validation failed for '#{field}': length must be <= #{max}")
    end

    def self.validate_items(field, value, min: nil, max: nil)
      n = value.length
      if min && n < min
        raise SdkValidationError.new(field, 'items',
                                     "Validation failed for '#{field}': must have at least #{min} items")
      end
      return unless max && n > max

      raise SdkValidationError.new(field, 'items',
                                   "Validation failed for '#{field}': must have at most #{max} items")
    end

    EMAIL_RE = /\A[^\s@]+@[^\s@]+\.[^\s@]+\z/
    def self.validate_email(field, value)
      return if value =~ EMAIL_RE

      raise SdkValidationError.new(field, 'format:email',
                                   "Validation failed for '#{field}': must be a valid email address")
    end
  end
end
